name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Update README stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: "Sam" # change to your GitHub username
        run: |
          node <<'EOF'
          const fs = require('fs');
          const fetch = require('node-fetch');

          const token = process.env.GITHUB_TOKEN;
          const username = process.env.USERNAME;

          async function fetchStats() {
            const headers = { Authorization: `token ${token}` };

            // Fetch private repo count
            const reposRes = await fetch(`https://api.github.com/user/repos?per_page=100&type=private`, { headers });
            const repos = await reposRes.json();
            const privateCount = repos.length;

            // Fetch commit activity (total this year)
            const commitRes = await fetch(`https://api.github.com/search/commits?q=author:${username}+author-date:>${new Date().getFullYear()}-01-01`, {
              headers: { ...headers, Accept: 'application/vnd.github.cloak-preview' }
            });
            const commitData = await commitRes.json();
            const commitCount = commitData.total_count;

            // Update README
            let readme = fs.readFileSync('README.md', 'utf8');
            readme = readme.replace(/(<!--PRIVATE_REPOS-->).*/, `$1 ${privateCount}`);
            readme = readme.replace(/(<!--TOTAL_COMMITS-->).*/, `$1 ${commitCount}`);
            fs.writeFileSync('README.md', readme);
          }

          fetchStats();
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "chore: update stats"
          git push
