name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Update README stats
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }} # your existing PAT stored as secret
          USERNAME: "SamPaul Isaac" # change to your GitHub username
        run: |
          node <<'EOF'
          const fs = require('fs');
          const fetch = require('node-fetch');

          const token = process.env.GITHUB_TOKEN;
          const username = process.env.USERNAME;

          async function fetchStats() {
            const headers = { Authorization: `token ${token}` };

            // 1️⃣ Fetch private repo count + stars
            let privateRepoCount = 0;
            let totalStars = 0;
            let page = 1;
            while (true) {
              const reposRes = await fetch(`https://api.github.com/user/repos?per_page=100&page=${page}`, { headers });
              const repos = await reposRes.json();
              if (!repos.length) break;
              privateRepoCount += repos.filter(r => r.private).length;
              totalStars += repos.reduce((sum, r) => sum + (r.stargazers_count || 0), 0);
              page++;
            }

            // 2️⃣ Fetch total commits this year
            const year = new Date().getFullYear();
            const commitRes = await fetch(`https://api.github.com/search/commits?q=author:${username}+author-date:>=${year}-01-01`, {
              headers: { ...headers, Accept: 'application/vnd.github.cloak-preview' }
            });
            const commitData = await commitRes.json();
            const commitCount = commitData.total_count || 0;

            // 3️⃣ Fetch total contributions (commits + issues + PRs + reviews)
            let contributions = commitCount;

            // Issues created
            const issuesRes = await fetch(`https://api.github.com/search/issues?q=author:${username}+created:>=${year}-01-01+type:issue`, { headers });
            const issuesData = await issuesRes.json();
            contributions += issuesData.total_count || 0;

            // PRs created
            const prsRes = await fetch(`https://api.github.com/search/issues?q=author:${username}+created:>=${year}-01-01+type:pr`, { headers });
            const prsData = await prsRes.json();
            contributions += prsData.total_count || 0;

            // Reviews given
            const reviewsRes = await fetch(`https://api.github.com/search/issues?q=reviewed-by:${username}+created:>=${year}-01-01+type:pr`, { headers });
            const reviewsData = await reviewsRes.json();
            contributions += reviewsData.total_count || 0;

            // 4️⃣ Update README badges
            let readme = fs.readFileSync('README.md', 'utf8');
            readme = readme.replace(/(Private%20Repos-).*?-blue/, `$1${privateRepoCount}-blue`);
            readme = readme.replace(/(Commits%20This%20Year-).*?-green/, `$1${commitCount}-green`);
            readme = readme.replace(/(Total%20Stars-).*?-yellow/, `$1${totalStars}-yellow`);
            readme = readme.replace(/(Contributions-).*?-purple/, `$1${contributions}-purple`);
            fs.writeFileSync('README.md', readme);
          }

          fetchStats();
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "chore: update stats"
          git push
