name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Update README stats
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }} # <-- your existing token stored as PAT
          USERNAME: "SamPaul Isaac" # change to your GitHub username
        run: |
          node <<'EOF'
          const fs = require('fs');
          const fetch = require('node-fetch');

          const token = process.env.GITHUB_TOKEN;
          const username = process.env.USERNAME;

          async function fetchStats() {
            const headers = { Authorization: `token ${token}` };

            // Fetch private repo count
            let repoCount = 0;
            let page = 1;
            while (true) {
              const reposRes = await fetch(`https://api.github.com/user/repos?per_page=100&type=private&page=${page}`, { headers });
              const repos = await reposRes.json();
              if (!repos.length) break;
              repoCount += repos.length;
              page++;
            }

            // Fetch total commits this year
            const year = new Date().getFullYear();
            const commitRes = await fetch(`https://api.github.com/search/commits?q=author:${username}+author-date:>=${year}-01-01`, {
              headers: { ...headers, Accept: 'application/vnd.github.cloak-preview' }
            });
            const commitData = await commitRes.json();
            const commitCount = commitData.total_count || 0;

            // Update README with badge-compatible numbers
            let readme = fs.readFileSync('README.md', 'utf8');
            readme = readme.replace(/(Private%20Repos-).*?-blue/, `$1${repoCount}-blue`);
            readme = readme.replace(/(Commits%20This%20Year-).*?-green/, `$1${commitCount}-green`);
            fs.writeFileSync('README.md', readme);
          }

          fetchStats();
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "chore: update stats"
          git push
